services:
  file-manager:
    build: .
    env_file: .
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - /var/private/uploads:/app/uploads
      - /var/private/users.db:/app/users.db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
  nginx:
    build: ./nginx
    volumes:
      - /var/private/ssl:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/certbot
    depends_on:
      - file-manager
    ports:
      - "80:80"
      - "443:443"
    restart: always
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /var/private/ssl:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email your@email.com --agree-tos --no-eff-email -d your.domain.com
volumes:
  certbot-var:
  webroot:


