services:
  file-manager:
    build: .
    container_name: file-manager
    env_file: .env
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - /var/private/uploads:/app/uploads
      - /var/private/users.db:/app/users.db
      - /var/private/new_users.db:/app/new_users.db
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - /var/private/myfiles-kai.ru/ssl:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/certbot
    depends_on:
      - file-manager
    ports:
      - "80:80"
      - "443:443"
    restart: always
volumes:
  certbot-var:
  webroot:
